services:
  mongo:
    image: mongo:latest
    container_name: "news_summarizer_mongo"
    logging:
      options:
        max-size: 1g
    env_file: ".env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - local
    restart: always

  mysql:
    image: mysql:8.0
    container_name: zenml_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql

  zenml:
    image: zenmldocker/zenml-server
    container_name: zenml_server
    ports:
      - "8237:8080"
    environment:
      - ZENML_STORE_URL=mysql://root:password@host.docker.internal/zenml
      - ZENML_DEFAULT_USER_NAME=username
      - ZENML_DEFAULT_USER_PASSWORD=password

    links:
      - mysql
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure

volumes:
  mongo_data:
  mysql_data:

networks:
  local:
    driver: bridge
